import 'package:srilankan_breeds/model/dogmodel.dart';

const String appName = "Sri lankan Breeds";
const String slogan = "Dog App";
const String bgimage = 'assets/images/jamie-street-8rmYDezMIE4-unsplash.jpg';
const String logingString = "LOGIN";
const String forgetText = "Forgot password ?";
const List<String> dropDownValues = [
  'Labrador',
  'German Shepard',
  'Labrador Retriever',
  'Golden Retriever	',
  'Poodle',
  'Bulldog',
  'Pittbull',
  'Siberian Husky',
  'Pug',
  'Dachshund',
  'Rottweiler',
  'Pomenarian',
  'Greate Dane',
  'Boxer',
  'Dobermen',
  'shih Tzu',
  'St.Bernard',
  'English Spaniel	',
  'chow chow',
  'Bull Terrier',
  'Chow Chow '
      'kangal	',
  'German Shorthaired Pointer',
  'English Cocker Spaniel',
  'American pit Bull Terrier '
];
List<DogModel> dogList = [
  DogModel(
    id: 'id',
    breedName: 'Rottweiler',
    imageUrl:
        'https://image.shutterstock.com/image-photo/male-rottweiler-undocked-tail-park-260nw-1145589755.jpg',
    description:
        'The Rottweiler descends from dogs used by the Romans to drive the herds of cattle that fed the army as it marched through Europe.',
    imageUrlList: ['imageUrlList'],
    origin: 'German',
    lifeSpam: 10,
    temperament: 'temperament',
    size: 'size',
    weight: 50,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Labrador',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'St.Bernard',
    imageUrl:
        'https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.vetstreet.com%2Fdogs%2Fsaint-bernard&psig=AOvVaw3E5eQlZCPe3MAD18ONJICB&ust=1628276821863000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCIi30ovKmvICFQAAAAAdAAAAABAD',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
  DogModel(
    id: 'id',
    breedName: 'Breed Name',
    imageUrl:
        'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/07/09151754/Golden-Retriever-puppy-standing-outdoors-500x486.jpg',
    description: 'description',
    imageUrlList: ['imageUrlList'],
    origin: 'origin',
    lifeSpam: 3,
    temperament: 'temperament',
    size: 'size',
    weight: 30,
    femaleHeight: 'femaleHeight',
    femaleWeight: 'femaleWeight',
    maleHeight: 'maleHeight',
    maleWeight: 'maleWeight',
    otherName: ['otherName'],
  ),
];
